language: java

jdk:
  - openjdk8
  - oraclejdk8

addons:
  sonarcloud:
    organization: "redlink"
    token:
      secure: "TODO"

script:
  - mvn -B org.jacoco:jacoco-maven-plugin:prepare-agent test sonar:sonar