language: java

jdk:
  - openjdk8
  - oraclejdk8

jobs:
  include:
  - stage: sonarcloud
    jdk: openjdk8
    script:
      - mvn -B verify
        -Dsonar.login="${SONAR_TOKEN}"
        -Dsonar.branch.name="${TRAVIS_BRANCH}"

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
before_cache:
  - rm -rf $HOME/.m2/repository/io/chatpal/solr/solr-ext/
